application: iplfnf1
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  
- url: /csv
  static_dir: csv

- url: /static
  static_dir: static  

- url: /.*
  script: fnf_main.py